config/routes.rb
HbNote::Application.routes.draw do
  

  get "admin/index"
  get "/admin", to: "admin#index"
  get "admin/:username", to: "admin#user", as: "admin_user"
  get "admin/post"
  match "admin/:id", to: "admin#update", :via => :patch, as: "admin_ban"
  get "/blog/:username", to: "blog#index"
  # POST "admin/:username"
  # get "/blog/:id/d" to: "blog#show"
  get "blog/show"
  devise_for :users
  get "site/index"

  # root :to => "notebooks#index", :constraints => {user_signed_in?}
  root 'site#index'

  resources :notebooks do
    resources :notes
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/notebook.rb
class Notebook < ActiveRecord::Base

	belongs_to :user
	has_many :notes

	accepts_nested_attributes_for :user, :notes
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController

  layout "with_notebooks"

  # user_notebooks = @notebooks = current_user.notebooks.all
  # dont use @notebooks


  def index
    user_notebooks
  end

  def show
    user_notebooks
    @notebook = Notebook.find(params[:id])
    @notes = @notebook.notes
  end

  def new
    @notebook = current_user.notebooks.new
    # all notebooks for current user
    user_notebooks
  end

  def edit
    user_notebooks
    @notebook = current_user.notebooks.find(params[:id])
  end

  def create
    @notebook = current_user.notebooks.new(notebook_params)
    if @notebook.save
      redirect_to notebooks_path, notice: "Notebook successfully created"
    else
      redirect_to root_path
    end
  end

  def update
    @notebook = current_user.notebooks.find(params[:id])
    if @notebook.update_attributes(notebook_params)
      redirect_to @notebook, notice: "Notebook successfully updated"
    else
      redirect_to root_path, notice: "Error updating notebook"
    end
  end

  def destroy
    @notebook = current_user.notebooks.find(params[:id])
    @notebook.destroy
  end

  private
    def notebook_params
      params.require(:notebook).permit(:name, :description)
    end
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/views/notebooks/_notebooks.html.erb
<h3>Notebooks</h3>
  <% @notebooks.each do |notebook| %>
	  <% if notebook.name.present? %>
	    <p><%= link_to "#{notebook.name} (#{notebook.notes.count})", notebook %></p>
    <% end %>
  <% end %>

app/views/notebooks/destroy.html.erb
<h1>Notebooks#destroy</h1>
<p>Find me in app/views/notebooks/destroy.html.erb</p>

app/views/notebooks/edit.html.erb
<%= simple_form_for @notebook do |f| %>
  <%= f.input :name, :label => "Untitled notebook" %>
  <%= f.input :description, :label => "Notebook Contents" %>
  <%= f.button :submit, :class => "btn btn-large btn-info" %>
<% end %>

app/views/notebooks/index.html.erb
<h2><%= current_user.username %>'s Notebooks</h2>
<% @notebooks.each do |notebook| %>
  <div class="note-index">
  	<h3>+++++++++++</h3>
  	<p>
  		<h4><%= link_to notebook.name, notebook %></h4>
  		<%= link_to notebook.description, notebook %>
  	</p>
    <%= link_to "New Note", new_notebook_note_path(notebook),:class => "btn btn-large btn-info"  %>
    <h3>+++++++++++</h3>
  </div>
<% end %>

app/views/notebooks/new.html.erb
<h3>New Notebook</h3>
<%= simple_form_for @notebook do |f| %>
  <%= f.input :name, :label => "Untitled notebook" %>
  <%= f.input :description, :label => "Notebook Contents" %>
  <%= f.button :submit, :class => "btn btn-large btn-info" %>
<% end %>

app/views/notebooks/show.html.erb
<% if @notebook.notes.present? %>
	<h2>Notes</h2>
	<%= link_to "New Note", new_notebook_note_path(@notebook),:class => "btn btn-large btn-info" %>
	<br>
	<% @notebook.notes.each do |note| %>
	<div class="note-index">
		<h3>+++++++++++</h3>
				<h4><%= link_to note.title, notebook_note_path(@notebook, note) %></h4>
				<p><%= link_to markdown(truncate(note.body, :length => 20)), notebook_note_path(@notebook, note) %>
			</p>
		<h3>+++++++++++</h3>
	</div>
	<% end %>
<% else %>
	<h2>This Notebook has no notes</h2>
	<%= link_to "New Note", new_notebook_note_path(@notebook),:class => "btn btn-large btn-info"  %>
<% end %>

app/views/notebooks/update.html.erb
<h1>Notebooks#update</h1>
<p>Find me in app/views/notebooks/update.html.erb</p>