config/routes.rb
HbNote::Application.routes.draw do
  

  get "admin/index"
  get "/admin", to: "admin#index"
  get "admin/:username", to: "admin#user", as: "admin_user"
  get "admin/post"
  match "admin/:id", to: "admin#update", :via => :patch, as: "admin_ban"
  get "/blog/:username", to: "blog#index"
  # POST "admin/:username"
  # get "/blog/:id/d" to: "blog#show"
  get "blog/show"
  devise_for :users
  get "site/index"

  # root :to => "notebooks#index", :constraints => {user_signed_in?}
  root 'site#index'

  resources :notebooks do
    resources :notes
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/note.rb
class Note < ActiveRecord::Base

	belongs_to :notebook

	accepts_nested_attributes_for :notebook
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  layout "with_notebooks"
  
  # user_notebooks = @notebooks = current_user.notebooks.all
  # dont use @notebooks

  def index
    user_notebooks
  end

  def show
    user_notebooks
    @notebook = current_user.notebooks.find(params[:notebook_id])
    @note = Note.find(params[:id])
  end

  def new
    user_notebooks
    @notebook = current_user.notebooks.find(params[:notebook_id])
    @note = Note.new
  end

  def edit
    user_notebooks
    @notebook = current_user.notebooks.find(params[:id])
    @note = Note.find(params[:id])
  end

  def create
    @notebook = current_user.notebooks.find(params[:notebook_id])
    @note = current_user.notes.new(note_params)
    @note.notebook_id = params[:notebook_id]
    if @note.save
      redirect_to notebook_path(@notebook), notice: "Note successfully saved"
    else
      redirect_to notebook_path(@notebook), notice: "There was an error saving your note"
    end
  end

  def update
    @notebook = current_user.notebooks.find(params[:id])
    @note = Note.find(params[:id])
    if @note.update_attributes(note_params)
      redirect_to notebook_note_path(@notebook, @note), notice: "Note successfully updated"
    else
      redirect_to notebook_note_path(@notebook, @note), notice: "There was an error updating your note"
    end
  end

  def destroy
  end

  private
    def note_params
      params.require(:note).permit(:title, :body, :notebook_id, :public)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= simple_form_for [@notebook, @note] do |f| %>
      <%= f.input :title, :label => "Note Title" %>
      <%= f.input :body, :label => "Note Context" %>
      <%= f.input :public, label: "Publish to Blog", :as => :boolean %>
      <%= f.button :submit, :value => "Submit", :class => "btn btn-large btn-info" %>
      <% end %>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/destroy.html.erb
<h1>Notes#destroy</h1>
<p>Find me in app/views/notes/destroy.html.erb</p>

app/views/notes/edit.html.erb
<h3><%= @notebook.name %><h3>
<%= simple_form_for [@notebook, @note] do |f| %>
      <%= f.input :title, :label => "Note Title" %>
      <%= f.input :body, :label => "Note Context" %>
      <%= f.input :public, label: "Publish to Blog", :as => :boolean %>
      <%= f.button :submit, :value => "Submit", :class => "btn btn-large btn-info" %>
      <% end %>

app/views/notes/index.html.erb
<h1>Notes#index</h1>
<p>Find me in app/views/notes/index.html.erb</p>

app/views/notes/new.html.erb
<h3><%= @notebook.name %><h3>
<%= simple_form_for [@notebook, @note] do |f| %>
      <%= f.input :title, :label => "Note Title" %>
      <%= f.input :body, :label => "Note Context" %>
      <%= f.input :public, label: "Publish to Blog", :as => :boolean %>
      <%= f.button :submit, :value => "Submit", :class => "btn btn-large btn-info" %>
      <% end %>

app/views/notes/show.html.erb
<h1><%= @note.title %></h1>
<br>
<%= link_to "Edit Note", edit_notebook_note_path( @notebook, @note), :class => "btn btn-large btn-info" %>
<br>
<br>
<p><%= markdown(@note.body) %></p>

app/views/notes/update.html.erb
<h1>Notes#update</h1>
<p>Find me in app/views/notes/update.html.erb</p>