config/routes.rb
HbNote::Application.routes.draw do
  

  get "admin/index"
  get "/admin", to: "admin#index"
  get "admin/:username", to: "admin#user", as: "admin_user"
  get "admin/post"
  match "admin/:id", to: "admin#update", :via => :patch, as: "admin_ban"
  get "/blog/:username", to: "blog#index"
  # POST "admin/:username"
  # get "/blog/:id/d" to: "blog#show"
  get "blog/show"
  devise_for :users
  get "site/index"

  # root :to => "notebooks#index", :constraints => {user_signed_in?}
  root 'site#index'

  resources :notebooks do
    resources :notes
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/admin/index.html.erb
<h1>Admin Dashboard</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th>Allowed to publish?</th>
      <th>All Posts</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.banned ? "No" : "Yes" %></td>
      <td><%= link_to "All public posts", admin_user_path(user.username) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/post.html.erb
<h1>Admin#post</h1>
<p>Find me in app/views/admin/post.html.erb</p>

app/views/admin/user.html.erb
<h1>Moderate <%= @user.username %></h1>
<% if @posts.empty? %>
  <h3>The User has no public posts</h3>
<% else %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Post Title</th>
          <th>Allowed to publish?</th>
          <th>Update</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %> post id => <%= post.id %></td>
          <td><%= post.publishable? %></td>
          <td><%= button_to "Ban", admin_ban_path(post), :class => "btn btn-info", :method => :patch %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
<% end %>