config/routes.rb
HbNote::Application.routes.draw do
  

  get "admin/index"
  get "/admin", to: "admin#index"
  get "admin/:username", to: "admin#user", as: "admin_user"
  get "admin/post"
  match "admin/:id", to: "admin#update", :via => :patch, as: "admin_ban"
  get "/blog/:username", to: "blog#index"
  # POST "admin/:username"
  # get "/blog/:id/d" to: "blog#show"
  get "blog/show"
  devise_for :users
  get "site/index"

  # root :to => "notebooks#index", :constraints => {user_signed_in?}
  root 'site#index'

  resources :notebooks do
    resources :notes
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container" style="width: auto; padding: 0 20px;">
      <% if user_signed_in? %>
        <%= link_to "HB Note", notebooks_path, :class => "brand" %>
      <% else %>
        <a class="brand" href="/">HB Note</a>
      <% end %>
      <!-- <div class="nav-collapse collapse navbar-responsive-collapse"> -->
        <ul class="nav pull-right">
          <% if user_signed_in? %>
            <li><%= link_to "Admin", admin_path if can? :manage, :admin %></li>
            <li><%= link_to "My Notebooks", notebooks_path %></li>
            <li><%= link_to current_user.username.capitalize, edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      <!-- </div> -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HB Note</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render "layouts/header" %>

	<div class="container">
		<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		<% end %>
		<%= yield %>
		<%#= render "layouts/footer" %>
	</div>

</body>
</html>

app/views/layouts/with_notebooks.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HB Note</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	
	<%= render "layouts/header" %>

  <% if user_signed_in?%>
  	<div class="container">
      <div class="row">
        <div class="span3 my-notes">
          <%= render "/notebooks/notebooks" %>
        </div>
        
        <div class="span9">
          <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
          <% end %>
          <%= yield %>
          <%#= render "layouts/footer" %>
        </div>
      </div>
  	</div>

  <% else %>
  <!-- USER NOT SIGNED IN OR ON "SITE#INDEX"-->
    <div class="container">
      <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>
      <%= yield %>
  <% end %>

</body>
</html>